### DISCUSSION TITLE
How to use HA Postgres?

### DISCUSSION THREAD

**Discussion by RaymiiOrg** [gabe565/charts#654] [Q&A]
I'd like to use the HA bitnami chart for postgresql so my RSS reader could survive node failure better (https://artifacthub.io/packages/helm/bitnami/postgresql-ha). How would I go about to do that?

**Comment by gabe565** [comment]
Hey, sorry for the delay! I'd definitely like to add configuration to these charts (see #437), but at the moment I'd recommend setting the database envs manually.

I believe something like this? Replace `USERNAME` and `DATABASE` with your values (also make sure `postgresql-ha-postgresql` and `postgresql-ha-pgpool` is correct)
```yaml
env:
  DATABASE_PASSWORD:
    secretKeyRef:
      name: postgresql-ha-postgresql
      key: password
  DATABASE_URL: postgres://USERNAME:$(DATABASE_PASSWORD)@postgresql-ha-pgpool/DATABASE?sslmode=disable
```
