### ISSUE TITLE
[Tandoor] Unable to serve media files

### ISSUE THREAD

**Issue by TheGor1lla** [gabe565/charts#12]
Tried your chart today, works great with minimal configuration, but for some reason I get 404s when accessing anything under  media/
Saving media works, and Tandoors System View shows: 

Media Serving Ok
Everything is fine! 

https://github.com/TheGor1lla/homelab/tree/main/kubernetes/apps/housekeeping/tandoor/app

**Comment by TheGor1lla** [comment]
I misunderstood the example values, fixed it

**Comment by twaslows** [comment]
I ran into the same issue. For the record, the fix is to modify the ingress configuration:

```
ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: tandoor.example.com
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8080
          - path: /static
            service:
              port: 80
          - path: /media
            service:
              port: 80
```

As per [this commit](https://github.com/TheGor1lla/homelab/commit/a2511499fd466272c0c71e18ea4e013c9d5fbb6e) in @TheGor1lla's homelab repo.
