### ISSUE TITLE
[Headscale] How to use ACL file

### ISSUE THREAD

**Issue by dcshoes23** [gabe565/charts#126]
### Chart Name

headscale

### Chart Version

0.11.0

### Bug Description

For headscale ACLs, you need to set `HEADSCALE_ ACL_POLICY_PATH` env variable and point it to the location of your ACL policy file. How do you add this file with your chart?

**Comment by gabe565** [comment]
Good question! Let me take a look at the ACL policy config. It would probably make sense to add the ACL policy to a configmap. I'll send an example using the common library after I look at its config

**Comment by gabe565** [comment]
@dcshoes23 Thanks for bringing this to my attention! I just pushed v0.11.1 which adds built-in support for ACLs. To add it to your instance, add the following to your `values.yaml`:

```yaml
configMaps:
  acl:
    enabled: true
    data:
      policy: |
        {
          "acls": [
             ...
          ]
        }
```
