### ISSUE TITLE
Example for restricted-nameservers

### ISSUE THREAD

**Issue by SCLogo** [gabe565/charts#134]
### Chart Name

headscale

### Chart Version

0.11.1

### Problem

Please provide help for the following config for headscle :

```
dns_config:
  override_local_dns: true
  nameservers:
    - 1.1.1.1

  restricted_nameservers:
    foo.bar.com:
     - 1.1.1.1
    ```
