### ISSUE TITLE
Trouble with configuration

### ISSUE THREAD

**Issue by alexdresko** [gabe565/charts#2]
I kind of thought this would just work if I changed my helm chart's dependency from the k8s-at-home chart to yours, but that doesn't seem to be the case. No matter what kind of configuration I apply, the pod fails to start: 

```
terminated
Reason:Reason: StartError - exit code: 128
```

My chart.yaml:

```
dependencies:
  - name: homer
    version: 0.1.3
    repository: https://charts.gabe565.com
    # https://artifacthub.io/packages/helm/gabe565/homer
```

If I only include the following in my values.yaml, homer starts and runs fine at the provided ingress. 

```
homer:
  env:
    TZ: "America/New_York"
  persistence:
    config:
      enabled: true
  ingress:
    main:
      enabled: true
      hosts:
      - host: "{{ .Release.Name }}-exo-home.localtest.me"
        paths:
        - path: "/"  
```

But even if I use the config map from [your example](https://github.com/gabe565/charts/blob/main/charts/homer/values.yaml), I get the error:

```
homer:
  env:
    TZ: "America/New_York"
  persistence:
    config:
      enabled: true
  ingress:
    main:
      enabled: true
      hosts:
      - host: "{{ .Release.Name }}-exo-home.localtest.me"
        paths:
        - path: "/"          
  configmap:
    config:
      # -- Store homer configuration as a ConfigMap
      enabled: false
      # -- Homer configuration. [[ref]](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md)
      # @default -- See values.yaml
      data:
        config.yml: |
          externalConfig: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist
```

The pod logs are blank. 

I'm completely uninstalling and re-installing my umbrella chart to try to simulate a clean environment. 

I think the true error is this:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/cba4fcf1-ebe8-4f0e-a40f-070f7f9f6803/volume-subpaths/config/exo-demo-homer/0" to rootfs at "/www/assets": mount /var/lib/kubelet/pods/cba4fcf1-ebe8-4f0e-a40f-070f7f9f6803/volume-subpaths/config/exo-demo-homer/0:/www/assets (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown
```

Got any ideas?
