### ISSUE TITLE
qbittorrent - additional PV errors

### ISSUE THREAD

**Issue by boomam** [gabe565/charts#233]
### Chart Name

gabe565/qbittorrent

### Chart Version

0.2.2

### Bug Description

When deploying and specifying 'media' and 'downloads' as enabled, the following error gets generated, preventing deployment.
```
Error: INSTALLATION FAILED: execution error at (qbittorrent/templates/common.yaml:1:3): accessMode is required for PVC qbittorrent-1688408541-downloads
```
Setting media/downloads to false allows deployment.

### values.yaml

```yaml
Everything at default, other than the PV's section -

persistence:
  config:
    enabled: false
    retain: true
    storageClass: "test-class"
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: true
    mountPath: /media
  downloads:
    enabled: true
    mountPath: /downloads

```
Also tested by specifying the additional variables (class, retain, etc.) in each section, too.
Error persists.
```


### Relevant log output

_No response_

**Comment by gabe565** [comment]
@boomam Looks like I missed those in the docs, but you need to provide either `accessMode: ReadWriteOnce` or `accessMode: ReadWriteMany` for all persistent volumes! I believe you'll also need to set `size`. `storageClass` is optional if you plan to rely on the default.

One more thing: `/media` is not required. It could be useful if you plan to bind a Plex/Jellyfin media directory and have qBittorrent copy completed downloads, but only `/downloads` and `/config` are used by qBittorrent.

Based on your example, something like this should work:
```yaml
persistence:
  config:
    enabled: false
    retain: true
    storageClass: "test-class"
    accessMode: ReadWriteOnce
    size: 1Gi
  downloads:
    enabled: true
    storageClass: "test-class"
    accessMode: ReadWriteOnce
    size: 8Gi
```
