### ISSUE TITLE
Configurable Resources for Paperles

### ISSUE THREAD

**Issue by Cogitri** [gabe565/charts#358]
### Chart Name

paperless-ngx

### Is your feature request related to a problem? Please describe.

It'd be neat if paperless-ngx allowed to specify resource requests/limits

### Describe the solution you'd like

```
resources:
  requests:
    cpu:
    memory
[...]
```

**Comment by gabe565** [comment]
It does! The configuration can be set exactly like in your solution :)

**Comment by gabe565** [comment]
Although, similarly to the other open issue, this one will be changing soon due to a dependency chart upgrade. Currently, the config needs to look like this:
```yaml
resources:
  requests:
    cpu:
    memory:
```
but soon it will change to:
```yaml
controllers:
  main:
    containers:
      main:
        resources:
          requests:
            cpu:
            memory:
```
