### ISSUE TITLE
add support for an external database

### ISSUE THREAD

**Issue by fibbs** [gabe565/charts#437]
### Chart Name

paperless-ngx

### Describe the solution you'd like

I like to use [PGO operator](https://github.com/CrunchyData/postgres-operator) for all Postgres databases as it offers out-of-the-box upgrades, database backups, point-in-time restores etc. I would really like to use a PGO managed database for paperless-ngx, so I miss the option to use an external database in this helm chart.
Ideally would be an additional structure in the values.yaml like this:

```
externalPostgresql:
  enabled: true
  host: ""
  userName: ""
  password: ""
  dbName: ""
  existingSecret:
    secretName: ""
    userNameSecretKey: ""
    passwordSecretKey: ""
    hostSecretKey: ""
    dbNameSecretKey: ""
    postgresUserSecretKey: ""
```

With this example one could define wether to use an external database or not, and then chose from either using the values from the `host`, `userName`, `password` and other values, or to refer to an EXISTING secret and the keys within this secret being used. If one key would not be defined to be used in the existing secret, the appropriate "direct" option would be used, then.

Would a PR for such a feature be well received?

**Comment by gabe565** [comment]
At the moment, this is doable by setting the [Paperless-ngx database envs](https://docs.paperless-ngx.com/configuration/#database). I wouldn't be opposed to adding Helm values if more people prefer configuring them this way, but I usually try to keep the number of config values to a minimum in these charts. That keeps things simpler, and since the bjw-s common chart supports using hardcoded envs, valueFrom references, or envFrom, it's has been configurable enough for my use.

What do you think?

**Comment by gabe565** [comment]
Hmm I'm rethinking this. I think an externalDatabase config would make sense and shouldn't be too much trouble to add!

**Comment by chr0n1x** [comment]
@fibbs not sure if you figured this out for yourself;

I run CNPG on my cluster. So my values look something like this:

```yaml
paperless-ngx:
  # this prevents the template from using the bitnami chart
  postgresql:
    enabled: false

  # I have the cnpg operator spin up a cluster/instance in this namespace, which provisions the secret referenced below
  # so I force the env vars like this
  env:
    TZ: UTC
    PAPERLESS_DBENGINE: postgresql
    PAPERLESS_DBHOST: paperless-ngx-rw
    PAPERLESS_DBNAME: paperless_ngx
    PAPERLESS_DBUSER:
      valueFrom:
        secretKeyRef:
          name: paperless-ngx-superuser
          key: username 
    PAPERLESS_DBPASS:
      valueFrom:
       secretKeyRef:
         name: paperless-ngx-superuser
         key: password
```

now all this being said, the _resulting_ `values.yaml` is kind of confusing to read.

@gabe565 in my experience and as you already mentioned this is totally doable with your chart as it is.

fwiw though -- I personally dislike the bitnami charts (that's putting it lightly) because they're cumbersome to deal with, so a patch in this chart accounting for this kind of usecase would be welcome!
