### ISSUE TITLE
har(d)coded values | null-pointer

### ISSUE THREAD

**Issue by Gerrri** [gabe565/charts#466]
### Chart Name

paperless-ngx

### Chart Version

0.9.2

### Bug Description

Hey, I try to deploy the paperless-ngx chart via helmfile (helmfile below).

When i try to sync (apply) it i get this error:
`COMBINED OUTPUT:
  Release "paperless-ngx" does not exist. Installing it now.
  Error: template: paperless-ngx/templates/common.yaml:47:25: executing "paperless-ngx/templates/common.yaml" at <include "healthchecks.harcodedValues" .>: error calling include: template: paperless-ngx/templates/common.yaml:7:18: executing "healthchecks.harcodedValues" at <.Values.ingress.main>: nil pointer evaluating interface {}.main`

Are there any known issues with this topic?

### helmfile.yaml
```
repositories:
  - name: gabe565
    url: https://charts.gabe565.com

releases:
  - name: paperless-ngx
    namespace: "home-services"
    chart: gabe565/paperless-ngx
    version: 0.9.2
    values:
      - ingress:
        main:
          enabled: true
          annotations:
              kubernetes.io/ingress.class: traefik
          hosts:
          - host: hostname   
            paths:
              - path: /paperless
```

**Comment by gabe565** [comment]
@Gerrri This is due to the indentation of your ingress block. Try changing the following:
```yaml
      - ingress:
        main:
          enabled: true
          annotations:
              kubernetes.io/ingress.class: traefik
          hosts:
          - host: hostname   
            paths:
              - path: /paperless
```
to this:
```yaml
      - ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
            hosts:
              - host: hostname   
                paths:
                  - path: /paperless
```
