### ISSUE TITLE
Deployment stuck, pod is unhealthy

### ISSUE THREAD

**Issue by tadjik1** [gabe565/charts#493]
### Chart Name

bookstack

### Chart Version

0.14.0

### Problem

I'm using the default configuration (except for the ingress), and I see in logs that pod starts successfully. But it doesn't pass healthy check. I'm out of ideas what needs to be changed (since there is underlying dependency chart that creates services and deployments it's rather difficult to debug the problem. Maybe someone already faced this problem?

### values.yaml

```yaml
bookstack:
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns-enabled: ""
        external-dns.alpha.kubernetes.io/access: public
        nginx.ingress.kubernetes.io/auth-url: "https://auth.xxxxx/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.xxxxx/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        nginx.ingress.kubernetes.io/enable-access-log: "false"
      hosts:
        - host: xxxx
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: bookstack-certificate
          hosts:
            - xxxx

  service:
    main:
      ports:
        http:
          port: 8080

  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
```

### Relevant log output

```shell
in bookstack pod:

Waiting for DB to be available   INFO  Nothing to migrate.[custom-init] No custom files found, skipping...[ls.io-init] done.
```

k8s logs:
```
Startup probe failed: dial tcp 10.36.11.118:8080: connect: connection refused
```
```
