### ISSUE TITLE
Wrong Configmap Key in Homer Chart

### ISSUE THREAD

**Issue by kevinastone** [gabe565/charts#512]
### Chart Name

homer

### Chart Version

latest

### Bug Description

First, thanks for publishing these charts.  They're a huge help and time-saver.

I think there's a case issue in the configMap template for the `homer` chart.  To get the configMap to install in the pod deployment as a volume, I had to manually configure the persistence in my config `values.yaml` since the template looks for a `.Values.configmap.config.enabled`: https://github.com/gabe565/charts/blob/9effc81e76309155364e5b2f914fc48b3cd5bfbc/charts/homer/templates/common.yaml#L3

While the common library template uses `configMaps.config.enabled` to configure the config-map from the `values.yaml`: https://github.com/bjw-s/helm-charts/blob/6c25f4c536775ae89d89b220a2500e49d2394738/charts/library/common/values.yaml#L415

So, I think it's a simple `s/configmap/configMaps/g`

### values.yaml

```yaml
persistence:
  config:
    enabled: true
    type: configMap
    name: homer-config
    mountPath: /www/assets/config.yml
    subPath: config.yml

configMaps:
  config:
    # -- Store homer configuration as a ConfigMap
    enabled: true
    # -- Homer configuration. [[ref]](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md)
    # @default -- See [values.yaml](./values.yaml)
    data:
      config.yml: |
        <omitted>
```

### Relevant log output

```shell
[N/A]
```
