### ISSUE TITLE
Issue installing headscale

### ISSUE THREAD

**Issue by AdamJSoftware** [gabe565/charts#55]
Whenever I try to install headscale with this configuration I get the following error
```
Error: INSTALLATION FAILED: template: headscale/templates/common.yaml:74:25: executing "headscale/templates/common.yaml" at <include "headscale.harcodedValues" .>: error calling include: template: headscale/templates/common.yaml:32:58: executing "headscale.harcodedValues" at <first .hosts>: error calling first: runtime error: invalid memory address or nil pointer dereference 
```

Here is my config
```
env:
  HEADSCALE_DNS_CONFIG_BASE_DOMAIN: headscale.mydomain.com
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/juanfont/headscale
  tag: 0.20.0
ingress:
  main:
    enabled: true
persistence:
  config:
    enabled: true
    mountPath: /etc/headscale
postgresql:
  auth:
    database: headscale
    postgresPassword: 'somepassword'
  enabled: true
  primary:
    persistence:
      enabled: true
service:
  main:
    ports:
      grpc:
        enabled: true
        port: 50443
      http:
        port: 8080
      metrics:
        port: 9090
```

**Comment by gabe565** [comment]
This is due to your ingress config missing some values. I'll add some better error handling and update the docs, but to get ingress to work, you need to define the hostname (and preferably TLS). Here's an example from my personal values:

```yaml
    ingress:
      main:
        enabled: true
        hosts:
          - host: example.com
            paths:
              - path: /
        tls:
          - secretName: example.com-tls
            hosts:
              - example.com
```
