### ISSUE TITLE
Add support for secrets

### ISSUE THREAD

**Issue by waza-ari** [gabe565/charts#573]
### Chart Name

paperless-ngx

### Is your feature request related to a problem? Please describe.

Somewhat related to #437, it would be very helpful to have the ability to set environment variables from secrets.

### Describe the solution you'd like

it would be nice to either specifying literals for environment variables, or being able to use the config map ref or secret ref, pretty much like that:

```yaml
name: CODER_OIDC_CLIENT_SECRET
valueFrom:
  secretKeyRef:
    name: secretname
    key: oidc_secret
```

**Comment by gabe565** [comment]
This is supported by the upstream common library. Here's how you could set your example env: 
```yaml
env:
  CODER_OIDC_CLIENT_SECRET:
    valueFrom:
      secretKeyRef:
        name: secretname
        key: oidc_secret
```
