### ISSUE TITLE
add additionalVolumes and additionalVolumeMounts

### ISSUE THREAD

**Issue by mkshb** [gabe565/charts#595]
### Chart Name

paperless-nxg

### Is your feature request related to a problem? Please describe.

I would like to mount my consume and export directories via nfs from my NAS.

### Describe the solution you'd like

config additionalVolumes and additionalVolumeMounts in helm chart values

**Comment by mkshb** [comment]
Found the common library config. So it's already posible.

```
  consume:
      enabled: true
      type: nfs
      server: nfs-server-ip
      path: nfs-path
```
