### ISSUE TITLE
Unable to access VueTorrent

### ISSUE THREAD

**Issue by zozidalom** [gabe565/charts#699]
### Chart Name

qbittorrent

### Chart Version

0.3.7

### Bug Description

helmfile.yaml
```
  - name: qbittorrent
    namespace: qbittorrent
    chart: oci://ghcr.io/gabe565/charts/qbittorrent
    version: 0.3.7
    values:
      - env:
          TZ: Europe/Budapest
          DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
      - persistence:
          vuetorrent:
            enabled: true
            type: emptyDir
```

I have the following configuration and I don't see where to access the VueTorrent web interface.

When I open the webui using a port-forward ot my pod all I get is: Unauthorized with a 401 status reply. Not prompted even for http basic auth or anything. I didn't find any further information on artifacthub how to access the webui, so I would ask for some help here.

### values.yaml

```yaml
- env:
    TZ: Europe/Budapest
    DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
- persistence:
    vuetorrent:
      enabled: true
      type: emptyDir
```

### Relevant log output

```shell
[mod-init] Running Docker Modification Logic
[mod-init] Adding gabe565/linuxserver-mod-vuetorrent to container
[mod-init] Downloading gabe565/linuxserver-mod-vuetorrent from ghcr.io
[mod-init] Installing gabe565/linuxserver-mod-vuetorrent
[mod-init] gabe565/linuxserver-mod-vuetorrent applied to container
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
Linuxserver.io version: 4.6.6-r0-ls350
Build-date: 2024-09-15T06:53:09+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: mytemporarypasswordishere
You should set your own password in program preferences.
Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
```
