### ISSUE TITLE
Add ability to mount volume from host using hostPath

### ISSUE THREAD

**Issue by zozidalom** [gabe565/charts#700]
### Chart Name

qbittorrent

### Describe the solution you'd like

volumes: [] and volumeMounts: [] option in the chart with support for hostPath.

**Comment by gabe565** [comment]
@zozidalom This is supported by the upstream chart! See [this section](https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml#L492-L537). Basically, you can configure a `hostPath` mount like this:
```
persistence:
  data:
    enabled: true
    type: hostPath
    hostPath: /path/to/dir
```
