### ISSUE TITLE
NodeSelector

### ISSUE THREAD

**Issue by peterweissdk** [gabe565/charts#737]
### Chart Name

gotify

### Chart Version

0.4.0

### Bug Description

I want to use nodeSelector with the Gotify chart, but it's notprovided. I was looking in the https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml and found a option for nodeSelector. I implemented it in the values file, and it upgraded without any errors, but it did not moved the pod to the nodes i had selected.
What am I doing wrong ?
/peterweissdk

### values.yaml

```yaml
defaultPodOptions:
  nodeSelector:
    evironment: production # My labels for a group of production nodes
```

### Relevant log output

```shell

```
