### ISSUE TITLE
Headscale with UI requires API Key

### ISSUE THREAD

**Issue by qdrddr** [gabe565/charts#744]
### Chart Name

Headscale

### Chart Version

0.16.0

### Problem

When I setup my headscale server with ui, when I open UI, it requires to enter URL & API key for the headscale.
Where can I set API key for my headscale so I can use it with UI?

### values.yaml

```yaml
sidecars:
  ui:
    image: ghcr.io/gurucomputing/headscale-ui:2025.01.20
    ports:
      - name: http
        containerPort: 80
    env:
       # The latest major release of headscale ui change the default container ports from 80 and 443 to 8080 and 8443 respectively. 
       # If you are using the HTTP_PORT or HTTPS_PORT environment variables this does not affect you, otherwise you need to change your ports in your docker-compose or kubernetes manifests.
      - name: HTTP_PORT
        value: 80
      - name: HTTPS_PORT
        value: 443

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/juanfont/headscale
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v0.25.0

# -- Container args
args: ["serve"]



# https://github.com/gabe565/charts/tree/main/charts/headscale
# To keep config simple, this Helm chart suggests using environment variables. 
# All of the Headscale config variables are supported as envs, but official documentation is lacking.
# For any that you want to set: flatten object keys using _, then prefix with HEADSCALE_. 
# For example, the following original headscale server config:
# https://github.com/juanfont/headscale/blob/main/config-example.yaml
#disable_check_updates: true
#log:
#  level: warn

# would be set with the following Helm values:
#env:
#  HEADSCALE_DISABLE_CHECK_UPDATES: "true"
#  HEADSCALE_LOG_LEVEL: "warn"

# -- Environment variables. [[ref]](https://github.com/juanfont/headscale/blob/main/config-example.yaml)
# @default -- See [values.yaml](./values.yaml)
env:
  TZ: "America/Chicago"
  HEADSCALE_LOG_LEVEL: "warn"
  HEADSCALE_SERVER_URL: "https://skynet-hs.mywebsite.com"
  ## Use already defined certificates:
  HEADSCALE_TLS_CLIENT_AUTH: "false"
  HEADSCALE_TLS_LETSENCRYPT_HOSTNAME: ""
  HEADSCALE_TLS_CERT_PATH: "/certs/tls.crt"
  HEADSCALE_TLS_KEY_PATH: "/certs/tls.key"
  
  # -- Defines the base domain to create the hostnames for MagicDNS.
  # This domain _must_ be different from the server_url domain.
  HEADSCALE_DNS_BASE_DOMAIN: "skynet.witc"

  # HEADSCALE_OIDC_ISSUER: ""
  # HEADSCALE_OIDC_CLIENT_ID: ""
  # HEADSCALE_OIDC_CLIENT_SECRET: ""

  # -- Node IPv4 prefixes
  HEADSCALE_PREFIXES_V4: "100.64.0.0/10"
  # -- Node IPv6 prefixes
  HEADSCALE_PREFIXES_V6: "fd7a:115c:a1e0::/48"

  # -- List of DNS servers to expose to clients.
  HEADSCALE_DNS_NAMESERVERS_GLOBAL: "1.1.1.1 1.0.0.1"
  # -- Whether to use [MagicDNS](https://tailscale.com/kb/1081/magicdns/).
  HEADSCALE_DNS_MAGIC_DNS: "true"

  HEADSCALE_DERP_URLS: "https://controlplane.tailscale.com/derpmap/default"
  HEADSCALE_DERP_AUTO_UPDATE_ENABLED: "true"
  HEADSCALE_DERP_UPDATE_FREQUENCY: "24h"

  HEADSCALE_EPHEMERAL_NODE_INACTIVITY_TIMEOUT: "30m"

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080
      metrics:
        port: 9090
      grpc:
        enabled: false
        port: 50443
      # -- UI service for the sidecar
      ui:
        port: 80


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    hosts:
    # server_url (serverUrl)?
      - host: skynet-hs.mywebsite.com
        paths:
          - path: /
    tls:
      - secretName: skynet-hs.mywebsite.com-tls
        hosts:
          - skynet-hs.mywebsite.com
  # -- UI ingress for the sidecar
  ui:
    enabled: true
    hosts:
      - host: skynet-hs.mywebsite.com
        paths:
            # the UI will be available at /web
          - path: /web
            service:
              #port: 80
              port: 80
    tls:
      - secretName: skynet-hs.mywebsite.com-tls
        hosts:
          - skynet-hs.mywebsite.com

configMaps:
  acl:
    # -- Enables ACL policy
    enabled: false
    data:
      # -- ACL policy JSON [[ref]](https://tailscale.com/kb/1018/acls/)
      policy:
  dns:
    # -- Enables DNS extra records
    enabled: false
    data:
      # -- DNS extra records JSON [[ref]](https://headscale.net/development/ref/dns/#__tabbed_1_2)
      records:

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  config:
    enabled: true
    mountPath: /etc/headscale
    retain: true
    storageClass: "local-path-delete"
    accessMode: ReadWriteOnce
    size: 1Gi
  tls:
    enabled: true
    type: secret
    name: skynet-hs.mywebsite.com-tls
    mountPath: /certs
    readOnly: true


# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: false
  auth:
    database: headscale
    postgresPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: "local-path-delete"
      # size: 8Gi

serviceMonitor:
  main:
    # -- Enables or disables the serviceMonitor.
    enabled: false
    # -- Configures the endpoints for the serviceMonitor.
    # @default -- See [values.yaml](./values.yaml)
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        interval: 30s
        scrapeTimeout: 10s
```

### Relevant log output

![Image](https://github.com/user-attachments/assets/679e301f-e8c7-4e09-8143-5a722c6f842f)
